version: '3.9'

networks:
  opera-network:
    driver: bridge

services:
  app:
    build: ./app
    ports:
      - "2345:2345"
    volumes:
      - $OPERA_PATH:/var/opera
      - $GO_ETHEREUM_PATH:/var/go-ethereum
      - $OPERA_DATA_PATH:/root/.opera
    networks:
      - opera-network